# Generated by Django 4.2 on 2023-05-08 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_post_id_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='app_user',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.location'),
        ),
    ]
