# Generated by Django 4.2 on 2023-05-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_location_app_user_location_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_user',
            old_name='location_id',
            new_name='location',
        ),
    ]
