# Generated by Django 4.2 on 2023-05-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_location_id_app_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
    ]
