# Generated by Django 4.2 on 2023-05-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_post_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='url',
            new_name='imgurl',
        ),
    ]
