# Generated by Django 4.2 on 2023-05-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_url_track_imgurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_id',
            new_name='id',
        ),
    ]
